### PR TITLE
Change types to interfaces && fix typing

### PR DESCRIPTION
**Pull request by pmatyjasik**

### CODE REVIEW

**Comment by xdk78** [comment]
why?

**Comment by xdk78** [comment]
I cannot find any advantage of `interface` in this code base over `type`
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

**Comment by pmatyjasik** [comment]
> I cannot find any advantage of `interface` in this code base over `type` https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces
Revised to maintain consistency across files.

Some files were based on type and some on interface

**Comment by xdk78** [comment]
> > I cannot find any advantage of `interface` in this code base over `type` https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces
> 
> Revised to maintain consistency across files. Some files were based on type and some on interface

ok

**Review by xdk78 — APPROVED** [review]

**Pull request merged**
